# Generated by Django 3.1.6 on 2021-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('tell', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField(verbose_name='date published')),
                ('last_in_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
