# Generated by Django 3.1.6 on 2021-11-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0002_bre_input_sma'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputHour',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('end', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
