# Generated by Django 3.1.6 on 2021-11-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0003_inputhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputhour',
            old_name='datetime',
            new_name='date',
        ),
    ]
