# Generated by Django 3.1.6 on 2021-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0004_auto_20211127_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btc1M',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('end', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Btc4H',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('end', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Btc5M',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('end', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='bre',
            name='day',
            field=models.IntegerField(default=20, verbose_name='移動平均線（足）'),
        ),
    ]
