# Generated by Django 3.1.1 on 2022-09-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0007_auto_20220823_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
