# Generated by Django 3.1.1 on 2022-09-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0008_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_in_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=100)),
                ('first_money', models.IntegerField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('result', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rcords.name+', to='mytrade.users')),
            ],
        ),
    ]
