# Generated by Django 3.1.1 on 2022-09-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0009_auto_20220907_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
