# Generated by Django 3.1.1 on 2022-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytrade', '0010_auto_20220910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='times',
            field=models.FloatField(null=True),
        ),
    ]
